### PR TITLE
Setup knock gem

### PR DESCRIPTION
**Pull request by nsarno**
I reflected the changes in the documentation from this [pull request](https://github.com/auth0/docs/pull/180) to the Ruby on Rails API seed project.

Let me know what you think! Thanks :)

### CODE REVIEW

**Comment by mgonto** [comment]
This looks amazingly more simple :).

@hzalaz could you check it out and run it?

**Comment by hzalaz** [comment]
@nsarno looks ok but there is a small issue with the client secret. We provide the secret base64 url encoded but Knock treat is as it is and ruby-jwt expects the raw key so all signature validation fails. A quick workaround is to return the key decoded like:

```ruby
config.token_secret_signature_key = -> { JWT.base64url_decode Rails.application.secrets.auth0_client_secret }
```

**Comment by hzalaz** [comment]
Also after fixing the signature issue, the sample fails whenever trying to fetch the user from a model named `User` which is not included in the sample, and since this behaviour is in the library there is little we can do to change that. (Also the claim that holds de id of the user is "hardcoded" in the lib).
I submitted this issue https://github.com/nsarno/knock/issues/1 with an alternative to allow a little more control on how we fetch the user, and even allow some cases when the user is only stored in Auth0 and not in the local DB.

**Comment by nsarno** [comment]
I updated the seed to use the version 1.2 of the gem, where both issues are fixed.

**Comment by hzalaz** [comment]
Great @nsarno, just one more thing with `config.current_user_from_token`. If I download this sample and try to run it, I'll always get 401 cause there is no User model and if I create one I need to prepopulate the DB, and we want these samples to work from start so let's either return a Hash with user's id from `sub` claim (I'll say to create a User struct not a model but maybe it's too much)

**Comment by nsarno** [comment]
I tried with a User struct but it looked way too confusing as an example IMO, so I sticked with a simple hash.

I added tests, so you can test the project by running `rake`.

**Comment by hzalaz** [comment]
Thanks @nsarno, already merged

**Comment by nsarno** [comment]
Awesome :)

**Pull request merged**
